In [ ]:
import pandas as pd
import numpy as np
Airline=pd.read_csv("D:\Cricket score Analysis\Airline delay analysis\DimAirline_raw.csv")
Originairport=pd.read_csv("D:\Cricket score Analysis\Airline delay analysis\DimAirport_raw.csv")
Destinationairport=pd.read_csv("D:\Cricket score Analysis\Airline delay analysis\DimAirport_raw.csv")
Factflight=pd.read_csv("D:\Cricket score Analysis\Airline delay analysis\FactFlight_raw.csv")
Factflight.info()
Airline.AirlineKey.duplicated()
Originairport.AirportKey.duplicated()
dup=Factflight.FlightKey.duplicated()
Factflight.FlightKey.value_counts().sort_values(ascending=False)
Factflight.drop_duplicates(subset=['FlightKey'], keep='first', inplace=True)
Factflight.info()
Factflight.head(20)
Factflight.describe()
Factflight.sort_values(by='DepartureDelayMinutes',ascending=False)
glitch_indices=Factflight[Factflight.DepartureDelayMinutes==9999].index
Factflight.drop(index=glitch_indices,inplace=True)
Total_canceled_flight=Factflight.query("Cancelled==1")["FlightKey"].count()
Factflight.info()
Factflight.loc[Factflight['Cancelled']==1,'DepartureDelayMinutes']=np.nan
Factflight.loc[Factflight['Cancelled']==1,'ArrivalDelayMinutes']=np.nan
Factflight.query("Cancelled==1")[["DepartureDelayMinutes","ArrivalDelayMinutes"]]
Factflight.describe()
Factflight.DistanceMiles=Factflight.DistanceMiles.abs()
Factflight.describe()
Factflight.head(20)
Factflight["DateKey"]=pd.to_datetime(Factflight["DateKey"].astype("string"),format='%Y%m%d')
Factflight.info()
Factflight.head()

Factflight.loc[Factflight["Cancelled"]==0,"ArrivalDelayMinutes"].fillna(0)
Factflight.loc[Factflight["Cancelled"]==0,"DepartureDelayMinutes"].fillna(0)
Factflight.info()
Factflight.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20025 entries, 0 to 20024
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   FlightKey              20025 non-null  int64
 1   DateKey                20025 non-null  int64
 2   AirlineKey             20025 non-null  int64
 3   OriginAirportKey       20025 non-null  int64
 4   DestinationAirportKey  20025 non-null  int64
 5   FlightNumber           20025 non-null  object
 6   ScheduledDeparture     20025 non-null  object
 7   ScheduledArrival       20025 non-null  object
 8   DepartureDelayMinutes  19587 non-null  float64
 9   ArrivalDelayMinutes    19546 non-null  float64
 10  DistanceMiles          20025 non-null  int64
 11  Cancelled              20025 non-null  int64
 12  Diverted               20025 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 2.0+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   FlightKey              20000 non-null  int64
 1   DateKey                20000 non-null  int64
 2   AirlineKey             20000 non-null  int64
 3   OriginAirportKey       20000 non-null  int64
 4   DestinationAirportKey  20000 non-null  int64
 5   FlightNumber           20000 non-null  object
 6   ScheduledDeparture     20000 non-null  object
 7   ScheduledArrival       20000 non-null  object
 8   DepartureDelayMinutes  19565 non-null  float64
 9   ArrivalDelayMinutes    19523 non-null  float64
 10  DistanceMiles          20000 non-null  int64
 11  Cancelled              20000 non-null  int64
 12  Diverted               20000 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 2.1+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 19996 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   FlightKey              19996 non-null  int64
 1   DateKey                19996 non-null  int64
 2   AirlineKey             19996 non-null  int64
 3   OriginAirportKey       19996 non-null  int64
 4   DestinationAirportKey  19996 non-null  int64
 5   FlightNumber           19996 non-null  object
 6   ScheduledDeparture     19996 non-null  object
 7   ScheduledArrival       19996 non-null  object
 8   DepartureDelayMinutes  19561 non-null  float64
 9   ArrivalDelayMinutes    19519 non-null  float64
 10  DistanceMiles          19996 non-null  int64
 11  Cancelled              19996 non-null  int64
 12  Diverted               19996 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 2.1+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 19996 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   FlightKey              19996 non-null  int64
 1   DateKey                19996 non-null  datetime64[ns]
 2   AirlineKey             19996 non-null  int64
 3   OriginAirportKey       19996 non-null  int64
 4   DestinationAirportKey  19996 non-null  int64
 5   FlightNumber           19996 non-null  object
 6   ScheduledDeparture     19996 non-null  object
 7   ScheduledArrival       19996 non-null  object
 8   DepartureDelayMinutes  19561 non-null  float64
 9   ArrivalDelayMinutes    19505 non-null  float64
 10  DistanceMiles          19996 non-null  int64
 11  Cancelled              19996 non-null  int64
 12  Diverted               19996 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(7), object(3)
memory usage: 2.1+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 19996 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   FlightKey              19996 non-null  int64
 1   DateKey                19996 non-null  datetime64[ns]
 2   AirlineKey             19996 non-null  int64
 3   OriginAirportKey       19996 non-null  int64
 4   DestinationAirportKey  19996 non-null  int64
 5   FlightNumber           19996 non-null  object
 6   ScheduledDeparture     19996 non-null  object
 7   ScheduledArrival       19996 non-null  object
 8   DepartureDelayMinutes  19561 non-null  float64
 9   ArrivalDelayMinutes    19505 non-null  float64
 10  DistanceMiles          19996 non-null  int64
 11  Cancelled              19996 non-null  int64
 12  Diverted               19996 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(7), object(3)
memory usage: 2.1+ MB

,FlightKey,DateKey,AirlineKey,OriginAirportKey,DestinationAirportKey,FlightNumber,ScheduledDeparture,ScheduledArrival,DepartureDelayMinutes,ArrivalDelayMinutes,DistanceMiles,Cancelled,Diverted
0,100001,2025-06-03,105,221,228,3692,05:15:00,09:48:00,12.0,4.0,1750,0,0
1,100002,2025-12-18,102,201,220,2337,08:30:00,11:16:00,5.0,1.0,950,0,0
2,100003,2025-09-26,102,203,229,1094,10:15:00,11:28:00,-2.0,0.0,250,0,0
3,100004,2025-08-10,104,213,210,6228,12:00:00,14:00:00,10.0,6.0,600,0,0
4,100005,2025-03-06,103,207,217,982,15:10:00,21:30:00,1.0,-11.0,2550,0,0

In [46]:
Airline.info()
Airline.head(12)
Airline["AirlineCode"]=Airline["AirlineCode"].astype("string").str.strip()
Airline["AirlineName"]=Airline["AirlineName"].astype("string").str.strip()
Airline["AirlineType"]=Airline["AirlineType"].astype("string").str.strip()
Airline.info()
Airline.head(12)
Airline.AirlineType=Airline.AirlineType.str.title()
Airline.head(12)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AirlineKey   12 non-null     int64
 1   AirlineCode  12 non-null     object
 2   AirlineName  12 non-null     object
 3   AirlineType  12 non-null     object
dtypes: int64(1), object(3)
memory usage: 512.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AirlineKey   12 non-null     int64
 1   AirlineCode  12 non-null     string
 2   AirlineName  12 non-null     string
 3   AirlineType  12 non-null     string
dtypes: int64(1), string(3)
memory usage: 512.0 bytes

    AirlineKey AirlineCode           AirlineName     AirlineType
0          101          AA     American Airlines    Full-Service
1          102          DL       Delta Air Lines    Full-Service
2          103          UA       United Airlines    Full-Service
3          104          WN    Southwest Airlines        Low-Cost
4          105          B6       JetBlue Airways        Low-Cost
5          106          AS       Alaska Airlines    Full-Service
6          107          NK       Spirit Airlines  Ultra Low-Cost
7          108          F9     Frontier Airlines  Ultra Low-Cost
8          109          HA     Hawaiian Airlines    Full-Service
9          110          G4         Allegiant Air  Ultra Low-Cost
10         111          SY  Sun Country Airlines        Low-Cost
11         112          9E          Endeavor Air        Regional

In [47]:
Originairport.info()

Originairport.duplicated().any()
Originairport.head(40)
Originairport["AirportName"]=Originairport["AirportName"].astype("string").str.strip()
Originairport["City"]=Originairport["City"].astype("string").str.strip()
Originairport["State"]=Originairport["State"].astype("string").str.strip()
Originairport["AirportCode"]=Originairport["AirportCode"].astype("string").str.strip()
Originairport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AirportKey   40 non-null     int64
 1   AirportCode  40 non-null     object
 2   AirportName  40 non-null     object
 3   City         40 non-null     object
 4   State        40 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AirportKey   40 non-null     int64
 1   AirportCode  40 non-null     string
 2   AirportName  40 non-null     string
 3   City         40 non-null     string
 4   State        40 non-null     string
dtypes: int64(1), string(4)
memory usage: 1.7 KB

In [48]:
Destinationairport.info()

Destinationairport.duplicated().any()
Destinationairport.head(40)
Destinationairport["AirportName"]=Destinationairport["AirportName"].astype("string").str.strip()
Destinationairport["City"]=Destinationairport["City"].astype("string").str.strip()
Destinationairport["State"]=Destinationairport["State"].astype("string").str.strip()
Destinationairport["AirportCode"]=Destinationairport["AirportCode"].astype("string").str.strip()
Destinationairport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AirportKey   40 non-null     int64
 1   AirportCode  40 non-null     object
 2   AirportName  40 non-null     object
 3   City         40 non-null     object
 4   State        40 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AirportKey   40 non-null     int64
 1   AirportCode  40 non-null     string
 2   AirportName  40 non-null     string
 3   City         40 non-null     string
 4   State        40 non-null     string
dtypes: int64(1), string(4)
memory usage: 1.7 KB

In [49]:
avg_Departdelayedtime=Factflight.DepartureDelayMinutes.mean()
avg_arrivaldelayedtime=Factflight.ArrivalDelayMinutes.mean()
cancelled_flight=Factflight.query("Cancelled==1")['Cancelled'].sum()
print(f"Total number of flight cancelled is:{cancelled_flight}")
Diverted_flight=Factflight.query("Diverted==1")['Diverted'].sum()
print(f"Total number of flights diverted is:{Diverted_flight}")
completed=len(Factflight)-cancelled_flight
print(f"Totao No. of completed flight is:{completed}")
departdelay_count=Factflight.query("DepartureDelayMinutes > 15")['FlightKey'].count()
print(f"Count of dparture delayed flights:{departdelay_count}")
arrivaldelay_count=Factflight.query("ArrivalDelayMinutes>15")['FlightKey'].count()
print(f"Count of arrival delayed flights:{arrivaldelay_count}")
cancel_rate=(cancelled_flight/len(Factflight) * 100).round()
print(f"flight cancelation rate:{cancel_rate}")
departdelay_rate=(departdelay_count/completed * 100).__round__(2)
print(f"The departure delay rate is:{departdelay_rate}")
arrivaldelay_rate=(arrivaldelay_count/completed * 100).round()
print(f"The arrival delay rate is:{arrivaldelay_rate}")

Total number of flight cancelled is:435
Total number of flights diverted is:56
Totao No. of completed flight is:19561
Count of dparture delayed flights:5514
Count of arrival delayed flights:5304
flight cancelation rate:2.0
The departure delay rate is:28.19
The arrival delay rate is:27.0

In [50]:
merged=pd.merge(Factflight,Airline,on="AirlineKey",how="left")
s=merged[(merged["Cancelled"]==0) & (merged["DepartureDelayMinutes"]>15)].groupby("AirlineType").agg(
    Flight_count=("ArrivalDelayMinutes","count")
)
print(s)
s1=merged[(merged["Cancelled"]==0) & (merged["ArrivalDelayMinutes"]>15)].groupby("AirlineType").agg(
    Flight_count=("FlightKey","count")
)
print(s1)

                Flight_count
AirlineType
Full-Service            3235
Low-Cost                1500
Regional                 122
Ultra Low-Cost           644
                Flight_count
AirlineType
Full-Service            3129
Low-Cost                1428
Regional                 120
Ultra Low-Cost           627

In [51]:
Factflight.to_csv("Cleaned Factflight",index=False)
Originairport.to_csv("Cleaned OriginAirport",index=False)
Airline.to_csv("cleaned Airline",index=False)
Destinationairport.to_csv("Cleanded Destinationairport",index=False)